# Generated by Django 4.0.6 on 2023-02-03 21:59

import app_goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app_goods.models.user_directory_path)),
            ],
        ),
    ]
