# Generated by Django 4.1.6 on 2023-02-06 20:45

import app_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=app_blog.models.user_directory_path, verbose_name='Images (model)'),
        ),
    ]
