# Generated by Django 4.0.6 on 2023-01-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('publisher', models.CharField(max_length=30, verbose_name='Кто опубликовал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'permissions': {('can_verify', 'Может ппроверить')},
            },
        ),
    ]
