# Generated by Django 4.0.6 on 2023-01-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_news',
            field=models.IntegerField(default=0),
        ),
    ]
