# Generated by Django 4.1.5 on 2023-01-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('order_num', models.CharField(max_length=4)),
                ('rqg_time', models.DateTimeField()),
            ],
        ),
    ]
