# Generated by Django 4.1.5 on 2023-01-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('small_num', models.PositiveSmallIntegerField(blank=True)),
                ('reg_time', models.DateTimeField(blank=True)),
                ('premium', models.BooleanField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
