# Generated by Django 4.1.5 on 2023-01-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='premium',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='reg_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_num',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
