# Generated by Django 4.1.5 on 2023-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_product_price_alter_product_reg_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
