# Generated by Django 4.0.6 on 2023-01-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
