# Generated by Django 4.0.6 on 2023-02-03 21:44

import app_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=app_media.models.user_directory_path),
        ),
    ]
